# Generated by Django 3.2.3 on 2021-05-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0003_auto_20210531_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_h',
            field=models.IntegerField(null=True),
        ),
    ]
