# Generated by Django 3.2.3 on 2021-05-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=20)),
                ('context_ellipsis', models.TextField()),
                ('name', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
