# Generated by Django 3.2.3 on 2021-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('registration_date', models.TextField()),
                ('activity_date', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('context', models.TextField()),
                ('content', models.TextField()),
                ('time', models.DateTimeField(null=True)),
                ('start_h', models.IntegerField(null=True)),
                ('end_h', models.IntegerField(null=True)),
            ],
        ),
    ]
