# Generated by Django 3.2.3 on 2021-05-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0002_data_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end_h',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_h',
            field=models.IntegerField(default=-1),
        ),
    ]
