# Generated by Django 3.2.3 on 2021-05-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0002_auto_20210515_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_context_ellipsis',
            new_name='context_ellipsis',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_sort',
            new_name='sort',
        ),
    ]
