# Generated by Django 3.2.3 on 2021-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0003_auto_20210515_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.CharField(default='요일', max_length=10),
        ),
        migrations.AddField(
            model_name='data',
            name='day',
            field=models.CharField(default='일', max_length=10),
        ),
        migrations.AddField(
            model_name='data',
            name='hour',
            field=models.CharField(default='시', max_length=10),
        ),
        migrations.AddField(
            model_name='data',
            name='minute',
            field=models.CharField(default='분', max_length=10),
        ),
        migrations.AddField(
            model_name='data',
            name='month',
            field=models.CharField(default='월', max_length=10),
        ),
        migrations.AddField(
            model_name='data',
            name='year',
            field=models.CharField(default='년', max_length=10),
        ),
    ]
