# Generated by Django 3.2.3 on 2021-05-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0004_auto_20210531_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='end_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_h',
            field=models.IntegerField(default=0),
        ),
    ]
