# Generated by Django 3.2.3 on 2021-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0004_auto_20210516_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.TextField()),
                ('subject', models.TextField()),
                ('date', models.CharField(default='요일', max_length=10)),
                ('start_h', models.CharField(default='시작시간', max_length=10)),
                ('end_h', models.CharField(default='종료시간', max_length=10)),
            ],
        ),
    ]
