# Generated by Django 3.2.3 on 2021-05-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0005_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end_h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_h',
            field=models.IntegerField(),
        ),
    ]
