# Generated by Django 3.2.3 on 2021-05-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0006_auto_20210517_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='day',
        ),
        migrations.RemoveField(
            model_name='data',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='data',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='data',
            name='month',
        ),
        migrations.RemoveField(
            model_name='data',
            name='year',
        ),
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
