# Generated by Django 3.2.3 on 2021-05-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_table', '0007_auto_20210522_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('registration_date', models.TextField()),
                ('activity_date', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
